### PR TITLE
Keep src dir clean from test data

### PR DESCRIPTION
**Pull request by daschl**

### CODE REVIEW

**Comment by daschl** [comment]
I just meant to fix the paths, my rustfmt hook did some reformatting. If you don't mind you can merge if not I can fix it up

**Comment by vmx** [comment]
Having it without the rustfm changes would be great. Running rustfmt is on my TODO list :)

**Comment by daschl** [comment]
will fix it up in a bit

**Comment by daschl** [comment]
@vmx there you go

**Pull request merged**
