### PR TITLE
Move executable from main.rs to bin/ folder.

### PR DESCRIPTION
**Pull request by daschl**
Following rust/cargo best practices the main.rs should be
used if the main purpose of this crate is to produce an
executable. Libraries instead should put supplemental binaries
into the bin folder (http://doc.crates.io/manifest.html#the-project-layout).

run with `cargo run --bin=hello_world`

### CODE REVIEW

**Comment by vmx** [comment]
@daschl Have you looked into that stuff more closely? I wonder if the executable should even be in a different crate. In the end it should really be a consumer of the library. So perhaps using the workspaces stuff would make sense (I need to take a closer look at those (of course you're welcome to have a closer look as well :))

**Comment by daschl** [comment]
@vmx I think at this scale its fine to put it either in the bin directory if its related to auxiliary usage, and if its examples go use the examples/ folder. workspaces could also work but I wonder if its overkill if its just sample usage/prototyping usage.

**Comment by vmx** [comment]
Fair point, I'll merge it soon.

**Comment by vmx** [comment]
@daschl: Sorry for taking so long. Would you mind rebasing it?

**Pull request closed without merging**
